export enum DataType {
  AUDIO = 'AUDIO',
  VIDEO = 'VIDEO',
  IMAGE = 'IMAGE',
  PACKAGE = 'PACKAGE',
  CALL = 'CALL',
  CONTACT = 'CONTACT',
  SMS = 'SMS',
  NOTE = 'NOTE',
  BOOK = 'BOOK',
  FEED_ENTRY = 'FEED_ENTRY',
  DOC = 'DOC',
}

// String values match the server's Capability GraphQL enum items.
export enum Capability {
  MEDIA_TRASH = 'MEDIA_TRASH',
  MIRROR_AUDIO = 'MIRROR_AUDIO',
  DOC_PREVIEW = 'DOC_PREVIEW',
  IMAGE_SEARCH = 'IMAGE_SEARCH',
  MEDIA_SCAN = 'MEDIA_SCAN',
  SMS = 'SMS',
  CALLS = 'CALLS',
  CALL_PHONE = 'CALL_PHONE',
  CONTACTS = 'CONTACTS',
  PACKAGES = 'PACKAGES',
  NOTES = 'NOTES',
  FEEDS = 'FEEDS',
  SCREEN_MIRROR = 'SCREEN_MIRROR',
  IMAGE_EDITOR = 'IMAGE_EDITOR',
  LAN_SHARE = 'LAN_SHARE',
  DISK_MANAGER = 'DISK_MANAGER',
}
